// final global = {
//   "SeriousCases": 8,
//   "ActiveCases": 16582,
//   "NewDeaths": 0,
//   "TotalRecovered": 15738,
//   "latitude": "1.29027",
//   "name": "Singapore",
//   "bnName": "সিঙ্গাপুর",
//   "TotalCases": 32343,
//   "NewCases": 383,
//   "TotalDeaths": 23,
//   "RationPerMillion": 5533,
//   "longitude": "103.851959"
// };
// Generated by https://quicktype.io

class GlobalData {
  int seriousCases;
  int activeCases;
  int newDeaths;
  int totalRecovered;
  String latitude;
  String name;
  String bnName;
  int totalCases;
  int newCases;
  int totalDeaths;
  int rationPerMillion;
  String longitude;

  GlobalData({
    this.seriousCases,
    this.activeCases,
    this.newDeaths,
    this.totalRecovered,
    this.latitude,
    this.name,
    this.bnName,
    this.totalCases,
    this.newCases,
    this.totalDeaths,
    this.rationPerMillion,
    this.longitude,
  });
}
